### ISSUE TITLE
no worky worky with awesome-selfhosted

### ISSUE THREAD

**Issue by sentriz** [kvnxiao/sort-awesome-lists#1]
https://github.com/Kickball/awesome-selfhosted/blob/master/README.md

`sort-awesome-lists` shows a `0` for most links, even when there is a github repo in the "source code" button

cool project

**Comment by kvnxiao** [comment]
I've fixed it. This was me carelessly assuming that people would put their github source code links in the very beginning of each markdown bullet point list.

Here's a preview
https://gist.github.com/kvnxiao/27c14760cbec35b4e312e34c856b51a8

**Comment by sentriz** [comment]
very nice thank you
